/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.RelatorioController;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.util.HashMap;
import javax.swing.JOptionPane;
import model.Aluno;
import model.Relatorio;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Senai
 */
public class cadastroAta extends javax.swing.JInternalFrame {

    /**
     * Creates new form cadastroAta
     */
    Relatorio relatorio;
    RelatorioController relatoriocontroller;

    public cadastroAta() {
        initComponents();
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAta = new javax.swing.JTextPane();
        btnGravar_Ata = new javax.swing.JButton();
        lblAluno = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtAluno = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jblPesqusa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Imprimir = new javax.swing.JButton();

        setClosable(true);
        setMaximumSize(null);

        jScrollPane1.setViewportView(txtAta);

        btnGravar_Ata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1477189671_edit-add.png"))); // NOI18N
        btnGravar_Ata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravar_AtaActionPerformed(evt);
            }
        });

        lblAluno.setText("Nome Aluno");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1477190974_kappfinder.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Título:");

        jblPesqusa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/1477190974_kappfinder.png"))); // NOI18N
        jblPesqusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblPesqusaActionPerformed(evt);
            }
        });

        jLabel2.setText("Pesquisar");

        Imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/1479534805_vector_66_15.png"))); // NOI18N
        Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnGravar_Ata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblPesqusa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(btnGravar_Ata))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(txtAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jblPesqusa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravar_AtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravar_AtaActionPerformed
        cadastrar_Ata();
        limpacampo();
    }//GEN-LAST:event_btnGravar_AtaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pesquisaAluno(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jblPesqusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblPesqusaActionPerformed
        pesquisaRelatorio();
    }//GEN-LAST:event_jblPesqusaActionPerformed

    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
        relatorioAta();
    }//GEN-LAST:event_ImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Imprimir;
    private javax.swing.JButton btnGravar_Ata;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jblPesqusa;
    private javax.swing.JLabel lblAluno;
    private javax.swing.JTextField txtAluno;
    private javax.swing.JTextPane txtAta;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

    String caminhoRac = getCaminho() + "/src/report/Relatorio.jasper";

    private String getCaminho() {
        try {
            return new File("").getAbsolutePath();
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(null, "Erro ao carregar caminho do relatório" + ex);
        }
        return "";
    }
    
        public void relatorioAta() {
        if (relatoriocontroller == null) {
            relatoriocontroller = new RelatorioController();
        }
        try {
            JRResultSetDataSource relResul = new JRResultSetDataSource
            (relatoriocontroller.relatorioAta(Integer.parseInt(txtAluno.getText())));
            JasperPrint jpPrint = JasperFillManager.fillReport(caminhoRac, new HashMap(), relResul);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setDefaultCloseOperation(JasperViewer.DISPOSE_ON_CLOSE);
            jv.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao chamar o relatório " + ex);
        }
    }

    public void cadastrar_Ata() {
        if (txtAta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Relatorio Invalido");
            txtAta.grabFocus();
            return;
        }
        if ((relatorio == null) || (relatoriocontroller == null)) {
            relatorio = new Relatorio();
            relatoriocontroller = new RelatorioController();
        }
        relatorio.setAta(txtAta.getText());
        relatorio.setTitulo(txtTitulo.getText());
        relatorio.setAlunoid(Integer.parseInt(txtAluno.getText()));
        if (relatoriocontroller.insereRelatorio(relatorio)) {
            JOptionPane.showMessageDialog(null, "Relatorio Cadastrado com Sucesso");
        }
    }

    public void limpacampo() {
        relatorio = null;
        txtAta.setText("");
        txtTitulo.setText("");
        txtAluno.setText("");
        lblAluno.setText("Nome Aluno");
    }

    private void setAluno(Aluno aluno) {
        txtAluno.setText(aluno.getAlunoid() + "");
        lblAluno.setText(aluno.getNome_completo());
    }

    private void pesquisaAluno(int id) {
        PesquisaAluno pesquisaAluno;
        if (id == 0) {
            pesquisaAluno = new PesquisaAluno(null, closable);
            pesquisaAluno.setVisible(true);
        } else {
            pesquisaAluno = new PesquisaAluno(id);
        }
        setAluno(pesquisaAluno.getAlunoSelecionado());
    }

    private void setRelatorio(Relatorio relatorio) {
        txtTitulo.setText(relatorio.getTitulo());
        txtAta.setText(relatorio.getAta());

    }

    private void pesquisaRelatorio() {
        view.PesquisaAta pesquisaAta = new PesquisaAta(null, true);
        pesquisaAta.setVisible(true);
        relatorio = pesquisaAta.getRelatorioSelecionado();
        setRelatorio(relatorio);
        pesquisaAluno(relatorio.getAlunoid());
    }

}