/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.InstituicaoController;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import model.Instituicao;


/**
 *
 * @author Senai
 */
public class CadastroInstituição extends javax.swing.JInternalFrame {

    InstituicaoController instituicaoController;
    Instituicao instituicao;

    
    /**
     * Creates new form CadastroInstituição
     */
    public CadastroInstituição() {
        initComponents();
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtNatureza = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Cadastro da Instituição");

        jLabel1.setText("Nome:");

        jLabel3.setText("Natureza Administrativa:");

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });

        txtNatureza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNaturezaKeyTyped(evt);
            }
        });

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1477189671_edit-add.png"))); // NOI18N
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(txtNatureza))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGravar)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNatureza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGravar)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        if (evt.getKeyChar() == 10) {
            txtNatureza.grabFocus();
        }
    }//GEN-LAST:event_txtNomeKeyTyped

    private void txtNaturezaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNaturezaKeyTyped
        if (evt.getKeyChar() == 10) {
            btnGravar.grabFocus();
        }
    }//GEN-LAST:event_txtNaturezaKeyTyped

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        addInstituicao();
    }//GEN-LAST:event_btnGravarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNatureza;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

    private void addInstituicao() {

        if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Nome Invalido");
            txtNome.grabFocus();
            return;
        } else if (txtNatureza.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Natureza Invalido");
            txtNatureza.grabFocus();
            return;
        }
        if ((instituicao == null) || (instituicaoController == null)) {
            instituicao = new Instituicao();
            instituicaoController = new InstituicaoController();
        }
        instituicao.setNome(txtNome.getText());
        instituicao.setNatureza_administrativa(txtNatureza.getText());
        if (instituicaoController.insereInstituicao(instituicao)) {
            limpaCampos();
            JOptionPane.showMessageDialog(null, "Instituicao Cadastrada com Sucesso");
        }
    }

    private void limpaCampos() {
        instituicao = null;
        txtNome.setText("");
        txtNatureza.setText("");
    }
}
