/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Senai
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmnArquivo = new javax.swing.JMenu();
        jmiSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiCadatroInstituicao = new javax.swing.JMenuItem();
        jmiCadastroAluno = new javax.swing.JMenuItem();
        jmiCadastroAta = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiPesquisarInstituicao = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmnArquivo.setText("Arquivo");

        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmnArquivo.add(jmiSair);

        jMenuBar1.add(jmnArquivo);

        jMenu2.setText("Cadastro");

        jmiCadatroInstituicao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jmiCadatroInstituicao.setText("Cadastro Instituição");
        jmiCadatroInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadatroInstituicaoActionPerformed(evt);
            }
        });
        jMenu2.add(jmiCadatroInstituicao);

        jmiCadastroAluno.setText("Cadastro Aluno");
        jmiCadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroAlunoActionPerformed(evt);
            }
        });
        jMenu2.add(jmiCadastroAluno);

        jmiCadastroAta.setText("Cadastro Ata");
        jmiCadastroAta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroAtaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiCadastroAta);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Pesquisa");

        jmiPesquisarInstituicao.setText("Pesquisar Instituição");
        jmiPesquisarInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPesquisarInstituicaoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiPesquisarInstituicao);

        jMenuItem2.setText("Pesquisar Aluno");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiCadatroInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadatroInstituicaoActionPerformed
        CadastroInstituição cadastroInstituição = new CadastroInstituição();
        this.add(cadastroInstituição);
        cadastroInstituição.setVisible(true);
    }//GEN-LAST:event_jmiCadatroInstituicaoActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Deseja realmente sair");
        if (dialogResult == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiCadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroAlunoActionPerformed
        CadastroAluno cadastroAluno = new CadastroAluno();
        this.add(cadastroAluno);
        cadastroAluno.setVisible(true);
    }//GEN-LAST:event_jmiCadastroAlunoActionPerformed

    private void jmiCadastroAtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroAtaActionPerformed
        cadastroAta cadastroAta = new cadastroAta();
        this.add(cadastroAta);
        cadastroAta.setVisible(true);
    }//GEN-LAST:event_jmiCadastroAtaActionPerformed

    private void jmiPesquisarInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPesquisarInstituicaoActionPerformed
        
    }//GEN-LAST:event_jmiPesquisarInstituicaoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        ;
    }
    );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jmiCadastroAluno;
    private javax.swing.JMenuItem jmiCadastroAta;
    private javax.swing.JMenuItem jmiCadatroInstituicao;
    private javax.swing.JMenuItem jmiPesquisarInstituicao;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenu jmnArquivo;
    // End of variables declaration//GEN-END:variables
}
